name: Pedro Entringer
description: Partner at IConex Logística | Partner at SmartLoad | Sênior Full Stack | IT Consulting
meta_description: "Pedro Entringer | Developer"

lang: pt-BR
markdown: kramdown
highlighter: rouge

logo: https://pedroentringer.dev/assets/images/profile.jpg
paginate: 5
baseurl: https://pedroentringer.dev/
domain_name: 'https://pedroentringer.dev'
google_analytics: 'UA-165073538-1'
plugins: [jekyll-paginate]

permalink: /:categories/:title/

# Details for the RSS feed generator
url:            'https://pedroentringer.dev'
author:         'Pedro Entringer'
